name: CI Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

permissions:
  contents: read

jobs:
  build:
    name: Compile and Verify Build
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Verify Build Success
        run: |
          if (!(Test-Path "RequiemAutoMagicPatcher/bin/Release")) {
            Write-Error "Build failed: No output in bin/Release!"
            exit 1
          }
        shell: pwsh