name: Create Synthesis Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0 

      - name: Fetch all branches properly
        run: |
            git fetch origin main:refs/remotes/origin/main
            git branch --track main origin/main || true

      - name: Check if tag is on main branch
        run: |
          if ! git merge-base --is-ancestor $GITHUB_REF refs/heads/main; then
            echo "Tag is not on main branch. Skipping release."
            exit 1
          fi

      - name: Generate .synth file
        run: |
          echo '{
            "AddGitPatcher": {
              "Url": "https://github.com/Exouth/RequiemAutoMagicPatcher",
              "SelectedProject": "RequiemAutoMagicPatcher/RequiemAutoMagicPatcher.csproj"
            }
          }' > RequiemAutoMagicPatcher.synth

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            RequiemAutoMagicPatcher.synth
          body: "Automated release for version ${{ github.ref_name }}"
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
